### ISSUE TITLE
Problem About Id2idx

### ISSUE THREAD

**Issue by LittleWhite-Hai** [thanhtrunghuynh93/networkAlignment#1]
Hello,I'm currently using this framework  and I'm very appreciate your works on this framework.
However, I'm a little puzzled when I try to check the neighbors of a node during debugging, it seems like this problem is linked to the dict _id2idx_, can you give me some guide about it? Thank you for your works!

**Comment by jingzhengli** [comment]
I encountered the same issue : self.id2idx[conversion(k)] = v ----> self.id2idx[k] = v
the other issue is about the shape of  dict "self.G.nodes()" is twice the edge_feats in line 66 of networkwork_alignment.py
